In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('covid data.csv')
#Removing unknown values
for x in df.columns:
    df = df[df[x]!=97]
    df = df[df[x]!=98]
    df= df[df[x] != 99]
df['STATUS'] = df['STATUS'].apply(lambda x : x.replace('Cured', 'likely to cure').replace('Died','likely to die'))
df

,INTUBED,PNEUMONIA,AGE,DIABETES,ASTHMA,CARDIOVASCULAR,OBESITY,TOBACCO,ICU,STATUS
1,1,2,55,1,2,2,2,2,2,likely to die
3,2,2,24,2,2,2,2,2,2,likely to cure
4,2,2,30,2,2,2,2,2,2,likely to cure
8,2,1,59,1,2,2,2,1,1,likely to cure
16,2,1,45,2,2,2,2,2,2,likely to cure
...,...,...,...,...,...,...,...,...,...,...
523481,2,1,26,2,2,2,2,2,2,likely to cure
523484,2,2,64,1,2,2,2,2,2,likely to cure
523486,2,1,50,1,2,2,1,2,2,likely to cure
523495,2,2,65,1,2,2,2,2,2,likely to cure
523507,2,2,51,2,2,2,2,2,2,likely to cure

In [3]:
Q1 = df.AGE.quantile(0.25) 
Q2 = df.AGE.quantile(0.75)
Q1, Q2

(43.0, 66.0)

In [4]:
IQR = Q2 - Q1
IQR

23.0

In [5]:
lower_limit = Q1 - 1.5*IQR
upper_limit = Q2 + 1.5*IQR
lower_limit, upper_limit

(8.5, 100.5)

In [6]:
df[(df.AGE <lower_limit) | (df.AGE > upper_limit)]

,INTUBED,PNEUMONIA,AGE,DIABETES,ASTHMA,CARDIOVASCULAR,OBESITY,TOBACCO,ICU,STATUS
69,2,2,2,2,2,2,2,2,2,likely to cure
70,2,2,1,2,2,2,2,2,2,likely to cure
82,2,2,1,2,2,1,2,2,2,likely to cure
85,2,1,7,2,2,2,2,2,1,likely to cure
86,2,1,1,2,2,2,2,2,2,likely to cure
...,...,...,...,...,...,...,...,...,...,...
523373,2,2,2,2,2,2,2,2,2,likely to cure
523374,2,2,4,2,2,2,2,2,2,likely to cure
523387,2,2,3,2,2,2,2,2,2,likely to cure
523396,2,2,2,2,2,2,2,2,2,likely to cure
523418,2,1,3,2,2,2,2,2,2,likely to cure

In [26]:
df = df[(df.AGE >lower_limit) & (df.AGE < upper_limit)]
df.sample(20)

,INTUBED,PNEUMONIA,AGE,DIABETES,ASTHMA,CARDIOVASCULAR,OBESITY,TOBACCO,ICU,STATUS
156149,2,1,81,2,2,2,2,2,2,likely to cure
28410,2,1,46,2,2,2,2,2,2,likely to die
234405,1,1,72,1,2,1,2,2,2,likely to die
220092,2,2,22,2,2,2,2,2,2,likely to cure
25662,1,2,75,1,2,2,1,2,2,likely to die
194532,2,1,63,1,2,2,2,2,2,likely to cure
59654,2,2,47,2,2,2,2,2,2,likely to cure
172157,1,1,67,2,2,2,1,2,2,likely to die
369896,2,1,10,2,2,2,2,2,1,likely to cure
43079,2,2,77,1,2,2,2,2,2,likely to cure
61496,2,1,96,1,2,2,2,2,2,likely to cure
205777,2,1,74,2,2,2,2,2,2,likely to cure
280750,2,1,53,1,1,2,2,2,2,likely to cure
208827,2,2,31,2,2,2,2,2,2,likely to cure
462886,2,1,67,2,2,2,1,2,2,likely to cure
227874,2,1,56,1,2,2,2,2,1,likely to die
29654,2,2,65,2,2,2,2,2,2,likely to die
125304,2,1,56,2,2,2,2,2,2,likely to cure
71323,2,2,88,2,2,2,2,2,2,likely to cure
358186,2,1,48,1,2,1,2,2,2,likely to cure

In [30]:
x = df[['INTUBED', 'PNEUMONIA', 'AGE', 'DIABETES', 'ASTHMA', 'CARDIOVASCULAR',
       'OBESITY', 'TOBACCO', 'ICU']]
y = df.STATUS

In [31]:
from sklearn.model_selection import train_test_split as ttt
X_train,X_test,y_train,y_test = ttt(x,y ,test_size = 0.1,  random_state = 10)
model = LogisticRegression(max_iter=5000,C = 20)
model.fit(X_train,y_train)

LogisticRegression(C=20, max_iter=5000)

In [32]:
model.score(X_test,y_test)

0.7301616458486407

In [33]:
model.score(X_train,y_train)

0.7291013930703679